[profile.default]
optimizer_runs = 100000
src = 'src'
fs_permissions = [{ access = "read", path = "./deployments/"}]

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"
op = "${RPC_URL_OPTIMISM}"
goerli = "${RPC_URL_GOERLI}"

[etherscan]
mainnet = {key = "${ETHERSCAN_KEY_ETHEREUM}"}
op = {key = "${ETHERSCAN_KEY_OPTIMISM}"}
goerli = {key = "${ETHERSCAN_KEY_ETHEREUM}", url = "https://api-goerli.etherscan.io/api"}